[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "abl"
version = "0.1.3"
authors = [
  { name="LAMDA 2023" },
]
description = "ABL-Package"
readme = "README.md"
requires-python = ">=3.6"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "pyswip==0.2.9",
    "torch",
    "torchvision",
    "zoopt",
    "termcolor"
]

[project.urls]
Homepage = "https://github.com/AbductiveLearning/ABL-Package"
Issues = "https://github.com/AbductiveLearning/ABL-Package/issues"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]